version: "3"

services:
  android-emulator:
    restart: "no"
    image: android-emu:25
    container_name: android-emu
    hostname: android-emu
    environment:
      - container=docker
    ports:
      - "32808:6080" #VNC connection
      - "32809:5555" #Emulator adb
      - "32810:5554" #Emulator console
      - "32811:22"   #SSH
    volumes:
      - $PWD/projects:/home/android/projects
      - $HOME/.android:/home/android/.android
    devices:
      - /dev/kvm:/dev/kvm
